// In-process "apply the model" — the live rebuild that runs when the model is
// swapped/fetched. It reloads the ontology, regenerates a fresh overlay (so stale
// keys from the previous model are gone), and drops/recreates the projection
// tables to match the new model. No `prisma generate`, no server restart — the
// projections are raw-SQL (twin/projection-store) and commands dispatch
// dynamically from the model (see the generic command route), so a freshly
// applied model is immediately runnable.
//
// A tiny in-memory status object backs the UI loader while this runs.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { prisma } from "../db.js";
import { DomainError } from "../errors.js";
import { isSystemProject, requireTenant } from "../platform/tenancy/context.js";
import { eventLogOrgWhere } from "../platform/tenancy/event-scope.js";
import { createVersion, ensureOntologyResource } from "../platform/ontology-store/ontology-store.js";
import { QLERIFY_DIR, reloadOntology, getOntology, loadOntologyFromStrings, setProjectModel } from "../ontology/model.js";
import { applyModelTables, setMeta, type ApplyResult } from "./projection-store.js";
import { dataModelSignature } from "./sim.js";
import { resetTransactionalState } from "../simulator/runner.js";

export type ApplyPhase = "idle" | "loading-model" | "rebuilding-overlay" | "rebuilding-tables" | "done" | "error";

export interface ApplyStatus {
  phase: ApplyPhase;
  message: string;
  startedAt: number | null;
  finishedAt: number | null;
  dropped: string[];
  created: string[];
  error: string | null;
}

let status: ApplyStatus = {
  phase: "idle",
  message: "",
  startedAt: null,
  finishedAt: null,
  dropped: [],
  created: [],
  error: null,
};

export function applyStatus(): ApplyStatus {
  return status;
}

/** Replace the overlay with one freshly derived from the current model, so the
 * previous model's (now stale) event keys don't linger. order = topological
 * index, phase = 1; curate later for a multi-act ordering. */
function writeFreshOverlay(): void {
  const ont = getOntology();
  const order = ont.topologicalOrder();
  const events: Record<string, { order: number; phase: number }> = {};
  order.forEach((key, i) => (events[key] = { order: i, phase: 1 }));
  // NOTE: do NOT write `title` here. The title must follow the loaded model
  // (its primary bounded context); baking it into the overlay makes it stick
  // across model switches (a stale-label bug). overlay.title stays a manual,
  // opt-in override only.
  const overlay = {
    $comment: "Regenerated by the model apply. order = topological index, phase = 1.",
    events,
  };
  writeFileSync(join(QLERIFY_DIR, "overlay.json"), JSON.stringify(overlay, null, 2) + "\n");
}

/** Run the full in-process rebuild. Updates `status` as it goes (for the loader).
 * `resetOverlay` defaults true; pass false to keep a hand-curated overlay. */
export async function applyModel(opts: { resetOverlay?: boolean } = {}): Promise<ApplyResult> {
  // The rebuild reloads the on-disk model + calls resetTransactionalState (which
  // clears the SHARED EventLog + Prisma tables). It is therefore system-project
  // only — a project must never trip the global reset. Project tables are created
  // lazily and the project's model is its own CAS version.
  if (!isSystemProject()) {
    throw new DomainError("Model rebuild is only supported on the system default project.");
  }
  status = { phase: "loading-model", message: "Loading model…", startedAt: Date.now(), finishedAt: null, dropped: [], created: [], error: null };
  try {
    // 1) Make sure the latest workflow.json is the live ontology.
    reloadOntology();

    // 2) Regenerate the overlay ONLY if it's stale for this model (its keys are
    // from a previously-loaded model). When the overlay already matches the
    // model, keep it — so hand-curated order/phase/title survive a Rebuild.
    if (opts.resetOverlay !== false && getOntology().staleOverlayKeys.length > 0) {
      status = { ...status, phase: "rebuilding-overlay", message: "Rebuilding overlay…" };
      writeFreshOverlay();
      reloadOntology();
    }

    // 3) Clean slate: reset ALL transactional data so a model switch doesn't
    // carry the previous model's rows. resetTransactionalState clears the Ericsson
    // Prisma tables + the shared EventLog (keeps the site/line seeds); the gen_
    // projection tables are wiped by the drop/recreate below.
    status = { ...status, phase: "rebuilding-tables", message: "Resetting demo data + rebuilding tables…" };
    await resetTransactionalState();
    const result = await applyModelTables(getOntology());
    // Mark the data as belonging to the now-applied model.
    await setMeta("dataModel", dataModelSignature());

    status = {
      ...status,
      phase: "done",
      message: `Rebuilt: dropped ${result.dropped.length}, created ${result.created.length} table(s).`,
      finishedAt: Date.now(),
      dropped: result.dropped,
      created: result.created,
    };
    return result;
  } catch (err: any) {
    status = { ...status, phase: "error", message: "Apply failed.", finishedAt: Date.now(), error: err?.message ?? String(err) };
    throw err;
  }
}

/**
 * Set the ACTIVE (non-system) project's own model from a provided Qlerify export.
 * Stores it as a new version of the project's ontology (CAS) and rebuilds ONLY
 * this project's data plane — its own gen__p<project>_ tables + its own EventLog.
 * The system demo and every OTHER project are untouched (everything here is
 * project-scoped via the ALS context). Never reaches the system disk model or the
 * global resetTransactionalState.
 */
export async function setActiveProjectModel(workflow: string, overlay: string | null): Promise<{ versionId: string; seq: number; changed: boolean }> {
  const ctx = requireTenant();
  if (isSystemProject() || !ctx.projectId) {
    throw new DomainError("Setting a project model applies to a non-system project; the system project uses the demo model controls.");
  }
  // Validate it's a loadable Qlerify model BEFORE we touch anything.
  try {
    loadOntologyFromStrings(workflow, overlay);
  } catch (e: any) {
    throw new DomainError(`Invalid Qlerify model: ${e?.message ?? String(e)}`);
  }

  // Resolve (or self-heal-create) the project's "workflow" ontology, then store
  // the new content as its current version.
  let ont = await prisma.platOntology.findFirst({
    where: { organizationId: ctx.organizationId, projectId: ctx.projectId, name: "workflow" },
    select: { id: true },
  });
  if (!ont) {
    const proj = await prisma.platProject.findFirst({ where: { id: ctx.projectId, organizationId: ctx.organizationId }, select: { workspaceId: true } });
    const r = await ensureOntologyResource({ organizationId: ctx.organizationId, projectId: ctx.projectId, workspaceId: proj?.workspaceId ?? null, environmentId: null, name: "workflow", ownerId: ctx.principal.id });
    ont = { id: r.ontologyId };
  }
  const v = await createVersion(ctx.organizationId, ont.id, workflow, overlay, { source: "set", createdBy: ctx.principal.id });

  // Make the new model live for THIS request, then rebuild the project's data
  // plane for it: drop the project's old projection tables, create the new
  // model's, and clear the project's run history. All project-scoped.
  setProjectModel(ctx.projectId, workflow, overlay, v.manifestHash);
  await applyModelTables(getOntology());
  await prisma.eventLog.deleteMany({ where: eventLogOrgWhere() });

  return { versionId: v.versionId, seq: v.seq, changed: v.changed };
}
