// In-process "apply the model" — the live rebuild that runs when the model is
// swapped/fetched. It reloads the ontology, regenerates a fresh overlay (so stale
// keys from the previous model are gone), and drops/recreates the projection
// tables to match the new model. No `prisma generate`, no server restart — the
// projections are raw-SQL (twin/projection-store) and commands dispatch
// dynamically from the model (see the generic command route), so a freshly
// applied model is immediately runnable.
//
// A tiny in-memory status object backs the UI loader while this runs.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { QLERIFY_DIR, reloadOntology, getOntology } from "../ontology/model.js";
import { applyModelTables, type ApplyResult } from "./projection-store.js";

export type ApplyPhase = "idle" | "loading-model" | "rebuilding-overlay" | "rebuilding-tables" | "done" | "error";

export interface ApplyStatus {
  phase: ApplyPhase;
  message: string;
  startedAt: number | null;
  finishedAt: number | null;
  dropped: string[];
  created: string[];
  error: string | null;
}

let status: ApplyStatus = {
  phase: "idle",
  message: "",
  startedAt: null,
  finishedAt: null,
  dropped: [],
  created: [],
  error: null,
};

export function applyStatus(): ApplyStatus {
  return status;
}

/** Replace the overlay with one freshly derived from the current model, so the
 * previous model's (now stale) event keys don't linger. order = topological
 * index, phase = 1; curate later for a multi-act ordering. */
function writeFreshOverlay(): void {
  const ont = getOntology();
  const order = ont.topologicalOrder();
  const events: Record<string, { order: number; phase: number }> = {};
  order.forEach((key, i) => (events[key] = { order: i, phase: 1 }));
  // NOTE: do NOT write `title` here. The title must follow the loaded model
  // (its primary bounded context); baking it into the overlay makes it stick
  // across model switches (a stale-label bug). overlay.title stays a manual,
  // opt-in override only.
  const overlay = {
    $comment: "Regenerated by the model apply. order = topological index, phase = 1.",
    events,
  };
  writeFileSync(join(QLERIFY_DIR, "overlay.json"), JSON.stringify(overlay, null, 2) + "\n");
}

/** Run the full in-process rebuild. Updates `status` as it goes (for the loader).
 * `resetOverlay` defaults true; pass false to keep a hand-curated overlay. */
export async function applyModel(opts: { resetOverlay?: boolean } = {}): Promise<ApplyResult> {
  status = { phase: "loading-model", message: "Loading model…", startedAt: Date.now(), finishedAt: null, dropped: [], created: [], error: null };
  try {
    // 1) Make sure the latest workflow.json is the live ontology.
    reloadOntology();

    // 2) Regenerate the overlay ONLY if it's stale for this model (its keys are
    // from a previously-loaded model). When the overlay already matches the
    // model, keep it — so hand-curated order/phase/title survive a Rebuild.
    if (opts.resetOverlay !== false && getOntology().staleOverlayKeys.length > 0) {
      status = { ...status, phase: "rebuilding-overlay", message: "Rebuilding overlay…" };
      writeFreshOverlay();
      reloadOntology();
    }

    // 3) Drop + recreate the projection tables to match the model.
    status = { ...status, phase: "rebuilding-tables", message: "Rebuilding projection tables…" };
    const result = await applyModelTables(getOntology());

    status = {
      ...status,
      phase: "done",
      message: `Rebuilt: dropped ${result.dropped.length}, created ${result.created.length} table(s).`,
      finishedAt: Date.now(),
      dropped: result.dropped,
      created: result.created,
    };
    return result;
  } catch (err: any) {
    status = { ...status, phase: "error", message: "Apply failed.", finishedAt: Date.now(), error: err?.message ?? String(err) };
    throw err;
  }
}
