// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Side-effect registration of each generated command (handler + detect +
// DESCRIBE), keyed by HTTP route segment. Imported once at server startup
// (src/http/routes.ts) to mount routes and back /describe and /detect.
//
// No commands are generated for the current model. Run `npm run codegen` after
// a model swap to (re)populate this file; until then every command dispatches
// through the model-driven generic path in src/http/routes.ts.

export {};
