// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Side-effect registration of each generated command's detect() predicate and
// DESCRIBE text, keyed by HTTP route segment. Imported once at server startup
// (src/http/routes.ts) to back /commands/:bc/:name/describe and /detect.
import { register } from "./registry.js";
import * as orderMaterial from "../sap/purchase-order/order-material.logic.js";
import * as confirmOrderWithETA from "../sap/purchase-order/confirm-order-with-eta.logic.js";
import * as changeMaterialETA from "../sap/purchase-order/change-material-eta.logic.js";
import * as receiveMaterial from "../sap/purchase-order/receive-material.logic.js";

register("order-material", { commandName: "OrderMaterial", boundedContext: "SAP", handlerName: "orderMaterial", eventRef: "#/domainEvents/MaterialOrdered", role: "Buyer", detect: orderMaterial.detect, DESCRIBE: orderMaterial.DESCRIBE });
register("confirm-order-with-eta", { commandName: "ConfirmOrderWithETA", boundedContext: "SAP", handlerName: "confirmOrderWithETA", eventRef: "#/domainEvents/SupplierConfirmedOrderWithETA", role: "Supplier", detect: confirmOrderWithETA.detect, DESCRIBE: confirmOrderWithETA.DESCRIBE });
register("change-material-eta", { commandName: "ChangeMaterialETA", boundedContext: "SAP", handlerName: "changeMaterialETA", eventRef: "#/domainEvents/MaterialETAChanged", role: "Supplier", detect: changeMaterialETA.detect, DESCRIBE: changeMaterialETA.DESCRIBE });
register("receive-material", { commandName: "ReceiveMaterial", boundedContext: "SAP", handlerName: "receiveMaterial", eventRef: "#/domainEvents/MaterialReceivedAtSite", role: "Goods Receiving", detect: receiveMaterial.detect, DESCRIBE: receiveMaterial.DESCRIBE });
