// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Deterministic command skeleton for "Material ETA Changed" (command ChangeMaterialETA,
// bounded context SAP). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./change-material-eta.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
import { requireString } from "../../util/invariants.js";
import { apply } from "./change-material-eta.logic.js";

export interface ChangeMaterialETAArgs {
  id: string;
  confirmedEta: string;
}

/** Material ETA Changed — emitted by role "Supplier". */
export async function changeMaterialETA(args: ChangeMaterialETAArgs, role: Role) {
  assertRole(role, "Supplier");
  requireString("id", args.id);
  requireString("confirmedEta", args.confirmedEta);
  return apply({ args, role });
}
