// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Public command surface for the PurchaseOrder aggregate (SAP). Re-exports the
// generated handlers so existing importers (HTTP routes, the simulator runner,
// tests) keep a stable path: src/sap/purchase-order/commands.ts.
export { orderMaterial } from "./order-material.gen.js";
export { confirmOrderWithETA } from "./confirm-order-with-eta.gen.js";
export { changeMaterialETA } from "./change-material-eta.gen.js";
export { receiveMaterial } from "./receive-material.gen.js";
