// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Deterministic command skeleton for "Supplier Confirmed Order With ETA" (command ConfirmOrderWithETA,
// bounded context SAP). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./confirm-order-with-eta.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
import { requireString } from "../../util/invariants.js";
import { apply } from "./confirm-order-with-eta.logic.js";

export interface ConfirmOrderWithETAArgs {
  id: string;
  confirmedEta: string;
}

/** Supplier Confirmed Order With ETA — emitted by role "Supplier". */
export async function confirmOrderWithETA(args: ConfirmOrderWithETAArgs, role: Role) {
  assertRole(role, "Supplier");
  requireString("id", args.id);
  requireString("confirmedEta", args.confirmedEta);
  return apply({ args, role });
}
