// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Deterministic command skeleton for "Material Ordered" (command OrderMaterial,
// bounded context SAP). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./order-material.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
import { requireString } from "../../util/invariants.js";
import { apply } from "./order-material.logic.js";

export interface OrderMaterialArgs {
  id: string;
  requestedDate: string;
}

/** Material Ordered — emitted by role "Buyer". */
export async function orderMaterial(args: OrderMaterialArgs, role: Role) {
  assertRole(role, "Buyer");
  requireString("id", args.id);
  requireString("requestedDate", args.requestedDate);
  return apply({ args, role });
}
