// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.
//
// Deterministic command skeleton for "Material Received At Site" (command ReceiveMaterial,
// bounded context SAP). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./receive-material.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
import { requireString } from "../../util/invariants.js";
import { apply } from "./receive-material.logic.js";

export interface ReceiveMaterialArgs {
  id: string;
  actualReceiptDate: string;
}

/** Material Received At Site — emitted by role "Goods Receiving". */
export async function receiveMaterial(args: ReceiveMaterialArgs, role: Role) {
  assertRole(role, "Goods Receiving");
  requireString("id", args.id);
  requireString("actualReceiptDate", args.actualReceiptDate);
  return apply({ args, role });
}
