// Full-power connector runtime (Part 2.4). The "integrate to anything" engine.
//
// An AI-built connector is a plain ESM module — `.qlerify/connectors/<id>.mjs` —
// that exports `async fetchRows(ctx)` (and optionally `probe(ctx)`) and may import
// ANY npm package and speak ANY protocol (AWS SDK, pg, googleapis, soap, raw
// fetch…). Unlike the Part 2.3 authored body (HTTP-only, in-process, deny-scanned),
// this one is unrestricted — so it runs in an ISOLATED child `node` process with a
// wall-clock + heap budget. A connector that hangs, crashes, or runs wild kills
// only its own subprocess, never the server or the demo.
//
// SECURITY POSTURE (PoC, security deferred per the product direction): the
// subprocess gets the credentials blob via a file (not argv/env), a reduced env
// (no ANTHROPIC_API_KEY etc.), and a hard timeout. Process isolation REPLACES the
// deny-scan as the safety boundary. Real hardening (containers, egress policy,
// seccomp) drops in behind this same `runConnector` contract later.

import { spawn } from "node:child_process";
import {
  mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { EntitySchema } from "../../ontology/model.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
export const CONNECTORS_DIR = join(ROOT, ".qlerify", "connectors");

const RUN_BUDGET_MS = 30_000; // generous — real APIs + cold SDK init can be slow
const INSTALL_BUDGET_MS = 180_000; // npm install of a fat SDK over the network
const HEAP_MB = 512;

// ---------------------------------------------------------------------------
// Workspace — one shared dir so a fat SDK (e.g. @aws-sdk) installs once and every
// connector resolves it. Per-connector throwaway is the <id>.* files, not the deps.
// ---------------------------------------------------------------------------

function modulePath(id: string): string { return join(CONNECTORS_DIR, `${id}.mjs`); }
function credPath(id: string): string { return join(CONNECTORS_DIR, `${id}.cred.json`); }
function ctxPath(id: string): string { return join(CONNECTORS_DIR, `${id}.ctx.json`); }
function resultPath(id: string): string { return join(CONNECTORS_DIR, `${id}.result.json`); }
const RUNNER = join(CONNECTORS_DIR, "runner.mjs");

/** The generic child-process runner. Imports the connector by file URL, builds the
 * capability `ctx`, runs fetchRows/probe, and writes the result JSON to a file. It
 * is written verbatim (idempotent) so it ships with no separate build step. */
const RUNNER_SRC = `// AUTO-GENERATED by src/packs/connector/runtime.ts — do not edit.
import { readFileSync, writeFileSync } from "node:fs";
const [, , modUrl, ctxFile, credFile, outFile] = process.argv;
const input = JSON.parse(readFileSync(ctxFile, "utf8"));
let credentials = {};
try { credentials = JSON.parse(readFileSync(credFile, "utf8")); } catch {}
const trace = [];
const log = (m) => { trace.push(typeof m === "string" ? m : JSON.stringify(m)); };
const pick = (...k) => { for (const x of k) if (credentials && credentials[x] != null) return credentials[x]; return undefined; };
const ctx = {
  entity: input.entity,
  limit: input.limit,
  endpoint: input.endpoint,
  credentials,
  secret: pick("secret", "apiKey", "api_key", "token", "accessToken", "key", "password"),
  fetch: (...a) => globalThis.fetch(...a),
  log,
  trace,
};
async function main() {
  const mod = await import(modUrl);
  if (input.op === "probe" && typeof mod.probe === "function") {
    return { ok: true, probe: await mod.probe(ctx), trace };
  }
  if (typeof mod.fetchRows !== "function") throw new Error("connector must export 'async fetchRows(ctx)'");
  const rows = await mod.fetchRows(ctx);
  const arr = Array.isArray(rows) ? rows : (rows == null ? [] : [rows]);
  return { ok: true, rows: arr.slice(0, input.limit ?? 100), count: arr.length, trace };
}
main()
  .then((out) => { writeFileSync(outFile, JSON.stringify(out)); process.exit(0); })
  .catch((err) => {
    const msg = err && (err.stack || err.message) ? (err.stack || err.message) : String(err);
    writeFileSync(outFile, JSON.stringify({ ok: false, error: msg, trace }));
    process.exit(1);
  });
`;

export function ensureWorkspace(): void {
  mkdirSync(CONNECTORS_DIR, { recursive: true });
  const pkg = join(CONNECTORS_DIR, "package.json");
  if (!existsSync(pkg)) {
    writeFileSync(pkg, JSON.stringify({ name: "qlerify-connectors", private: true, type: "module", dependencies: {} }, null, 2) + "\n");
  }
  // Keep the runner current with this file's RUNNER_SRC on every ensure.
  writeFileSync(RUNNER, RUNNER_SRC);
}

// ---------------------------------------------------------------------------
// Module + credentials persistence
// ---------------------------------------------------------------------------

export function writeModule(id: string, code: string): string {
  ensureWorkspace();
  const clean = code.endsWith("\n") ? code : code + "\n";
  writeFileSync(modulePath(id), clean);
  return modulePath(id);
}

export function readModule(id: string): string | null {
  const p = modulePath(id);
  return existsSync(p) ? readFileSync(p, "utf8") : null;
}

export function moduleExists(id: string): boolean {
  return existsSync(modulePath(id));
}

/** Store the plaintext credentials blob (any shape). PoC — security deferred. */
export function writeCredentials(id: string, creds: Record<string, unknown>): void {
  ensureWorkspace();
  writeFileSync(credPath(id), JSON.stringify(creds ?? {}, null, 2) + "\n");
}

export function readCredentials(id: string): Record<string, unknown> {
  const p = credPath(id);
  if (!existsSync(p)) return {};
  try { return JSON.parse(readFileSync(p, "utf8")) as Record<string, unknown>; } catch { return {}; }
}

/** The credential FIELD NAMES present (never the values) — safe to show in chat. */
export function credentialKeys(id: string): string[] {
  return Object.keys(readCredentials(id));
}

/** Remove a connector's files (module + creds + scratch). Shared deps are left in
 * place. Returns true if a module file existed. */
export function deleteConnectorFiles(id: string): boolean {
  const had = moduleExists(id);
  for (const p of [modulePath(id), credPath(id), ctxPath(id), resultPath(id)]) {
    if (existsSync(p)) rmSync(p);
  }
  return had;
}

// ---------------------------------------------------------------------------
// Dependency detection + install
// ---------------------------------------------------------------------------

const NODE_BUILTINS = new Set([
  "assert", "buffer", "child_process", "cluster", "console", "crypto", "dgram",
  "dns", "events", "fs", "http", "http2", "https", "net", "os", "path",
  "perf_hooks", "process", "querystring", "readline", "stream", "string_decoder",
  "timers", "tls", "tty", "url", "util", "v8", "vm", "worker_threads", "zlib",
]);

/** Bare npm package specifiers imported by the code (deps to install). Strips
 * subpaths ("@aws-sdk/lib-dynamodb/foo" → "@aws-sdk/lib-dynamodb"), node: builtins,
 * and relative/absolute paths. */
export function scanImports(code: string): string[] {
  const specs = new Set<string>();
  const patterns = [
    /\bimport\s+(?:[\w*${}\n\s,]+\s+from\s+)?["']([^"']+)["']/g,
    /\bexport\s+[\w*${}\n\s,]+\s+from\s+["']([^"']+)["']/g,
    /\bimport\s*\(\s*["']([^"']+)["']\s*\)/g,
    /\brequire\s*\(\s*["']([^"']+)["']\s*\)/g,
  ];
  for (const re of patterns) {
    let m: RegExpExecArray | null;
    while ((m = re.exec(code))) {
      const raw = m[1]!;
      if (raw.startsWith(".") || raw.startsWith("/") || raw.startsWith("node:")) continue;
      const parts = raw.split("/");
      const pkg = raw.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0]!;
      if (NODE_BUILTINS.has(pkg)) continue;
      specs.add(pkg);
    }
  }
  return [...specs];
}

function isInstalled(pkg: string): boolean {
  return existsSync(join(CONNECTORS_DIR, "node_modules", ...pkg.split("/"), "package.json"));
}

export interface InstallResult { installed: string[]; skipped: string[]; ok: boolean; log: string; }

/** Install any not-yet-present deps into the shared workspace. Idempotent. */
export async function installDeps(deps: string[]): Promise<InstallResult> {
  ensureWorkspace();
  const want = [...new Set(deps)].filter(Boolean);
  const skipped = want.filter(isInstalled);
  const missing = want.filter((d) => !isInstalled(d));
  if (missing.length === 0) return { installed: [], skipped, ok: true, log: "" };

  return await new Promise<InstallResult>((resolve) => {
    const args = ["install", ...missing, "--no-audit", "--no-fund", "--loglevel=error", "--save"];
    const child = spawn("npm", args, { cwd: CONNECTORS_DIR, env: { ...process.env } });
    let log = "";
    const cap = (b: Buffer) => { log += b.toString(); if (log.length > 8000) log = log.slice(-8000); };
    child.stdout.on("data", cap);
    child.stderr.on("data", cap);
    const timer = setTimeout(() => { child.kill("SIGKILL"); }, INSTALL_BUDGET_MS);
    child.on("close", (code) => {
      clearTimeout(timer);
      const ok = missing.every(isInstalled);
      resolve({ installed: ok ? missing : missing.filter(isInstalled), skipped, ok, log: log.trim() });
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ installed: [], skipped, ok: false, log: `npm spawn failed: ${err.message}` });
    });
  });
}

// ---------------------------------------------------------------------------
// Run — isolated subprocess
// ---------------------------------------------------------------------------

export interface RunRequest {
  entity: EntitySchema;
  limit: number;
  endpoint?: string;
  op?: "fetchRows" | "probe";
}

export interface RunResult {
  ok: boolean;
  rows?: Array<Record<string, unknown>>;
  count?: number;
  probe?: { ok: boolean; detail?: string };
  error?: string;
  trace: string[];
}

/** Run a connector in an isolated child process under a wall-clock + heap budget.
 * Credentials are read from the connector's cred file by the child (not passed via
 * argv/env). Captures the child's stdout/stderr into the trace so a crash or a
 * console.log surfaces to the AI troubleshooter for the iterate-and-fix loop. */
export async function runConnector(id: string, req: RunRequest): Promise<RunResult> {
  ensureWorkspace();
  if (!moduleExists(id)) return { ok: false, error: `connector "${id}" has no code yet — build it first`, trace: [] };

  const input = { entity: req.entity, limit: req.limit, endpoint: req.endpoint, op: req.op ?? "fetchRows" };
  writeFileSync(ctxPath(id), JSON.stringify(input));
  if (!existsSync(credPath(id))) writeFileSync(credPath(id), "{}");
  if (existsSync(resultPath(id))) rmSync(resultPath(id));

  // Reduced env: give the child a PATH + HOME for module resolution and TLS, but
  // NOT the host's secrets (ANTHROPIC_API_KEY etc.). Credentials arrive via file.
  const childEnv: NodeJS.ProcessEnv = {
    PATH: process.env.PATH,
    HOME: process.env.HOME,
    NODE_OPTIONS: "",
  };

  const argv = [
    `--max-old-space-size=${HEAP_MB}`,
    RUNNER,
    pathToFileURL(modulePath(id)).href,
    ctxPath(id),
    credPath(id),
    resultPath(id),
  ];

  return await new Promise<RunResult>((resolve) => {
    const child = spawn(process.execPath, argv, { cwd: CONNECTORS_DIR, env: childEnv });
    let out = "";
    const cap = (b: Buffer) => { out += b.toString(); if (out.length > 16000) out = out.slice(-16000); };
    child.stdout.on("data", cap);
    child.stderr.on("data", cap);

    let timedOut = false;
    const timer = setTimeout(() => { timedOut = true; child.kill("SIGKILL"); }, RUN_BUDGET_MS);

    child.on("close", () => {
      clearTimeout(timer);
      const childOut = out.trim();
      let parsed: RunResult | null = null;
      if (existsSync(resultPath(id))) {
        try { parsed = JSON.parse(readFileSync(resultPath(id), "utf8")) as RunResult; } catch { /* fall through */ }
      }
      if (parsed) {
        // Fold the child's console output into the trace for visibility.
        if (childOut) parsed.trace = [...(parsed.trace ?? []), ...childOut.split("\n").slice(-20)];
        resolve(parsed);
        return;
      }
      const error = timedOut
        ? `connector exceeded the ${RUN_BUDGET_MS / 1000}s run budget (killed)`
        : `connector process produced no result${childOut ? `:\n${childOut}` : " and no output"}`;
      resolve({ ok: false, error, trace: childOut ? childOut.split("\n").slice(-20) : [] });
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ ok: false, error: `failed to start connector process: ${err.message}`, trace: [] });
    });
  });
}

/** List connector ids that have a module on disk (diagnostics). */
export function listConnectorIds(): string[] {
  if (!existsSync(CONNECTORS_DIR)) return [];
  return readdirSync(CONNECTORS_DIR)
    .filter((f) => f.endsWith(".mjs") && f !== "runner.mjs")
    .map((f) => f.slice(0, -4));
}
