// Pure content emitters for the deterministic scaffold. Each takes descriptors
// and returns a file's text — no I/O, so they are trivially testable and the
// generator (generate.ts) decides when to write.

import type { CommandDescriptor } from "./introspect.js";

const HEADER = `// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.`;

/** The {command}.gen.ts skeleton: role check + arg validation + call into apply(). */
export function genContent(d: CommandDescriptor): string {
  const validators = [...new Set(d.fields.filter((f) => f.required && f.validator).map((f) => f.validator!))].sort();
  const validatorImport = validators.length
    ? `import { ${validators.join(", ")} } from "../../util/invariants.js";\n`
    : "";
  const argsType = `${d.commandName}Args`;
  const fieldLines = d.fields.map((f) => `  ${f.name}${f.required ? "" : "?"}: ${f.tsType};`).join("\n");
  const validationLines = d.fields
    .filter((f) => f.required && f.validator)
    .map((f) => `  ${f.validator}(${JSON.stringify(f.name)}, args.${f.name});`)
    .join("\n");

  return `${HEADER}
//
// Deterministic command skeleton for "${d.eventName}" (command ${d.commandName},
// bounded context ${d.boundedContext}). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./${d.kebab}.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
${validatorImport}import { apply } from "./${d.kebab}.logic.js";

export interface ${argsType} {
${fieldLines}
}

/** ${d.eventName} — emitted by role "${d.role}". */
export async function ${d.handlerName}(args: ${argsType}, role: Role) {
  assertRole(role, ${JSON.stringify(d.role)});
${validationLines ? validationLines + "\n" : ""}  return apply({ args, role });
}
`;
}

/** The aggregate's commands.ts barrel: a stable import surface. */
export function barrelContent(ds: CommandDescriptor[], aggregate: string, bc: string): string {
  const exports = ds.map((d) => `export { ${d.handlerName} } from "./${d.kebab}.gen.js";`).join("\n");
  return `${HEADER}
//
// Public command surface for the ${aggregate} aggregate (${bc}). Re-exports the
// generated handlers so existing importers (HTTP routes, the simulator runner,
// tests) keep a stable path: src/${bc.toLowerCase()}/${ds[0]?.aggDir ?? ""}/commands.ts.
${exports}
`;
}

/** src/commands/registry.generated.ts — side-effect registration of detect/DESCRIBE. */
export function registryContent(ds: CommandDescriptor[]): string {
  const imports = ds
    .map((d) => `import * as ${d.handlerName} from "../${d.bcDir}/${d.aggDir}/${d.kebab}.logic.js";`)
    .join("\n");
  const regs = ds
    .map(
      (d) =>
        `register(${JSON.stringify(d.kebab)}, { commandName: ${JSON.stringify(d.commandName)}, boundedContext: ${JSON.stringify(d.boundedContext)}, handlerName: ${JSON.stringify(d.handlerName)}, eventRef: ${JSON.stringify(d.eventRef)}, role: ${JSON.stringify(d.role)}, detect: ${d.handlerName}.detect, DESCRIBE: ${d.handlerName}.DESCRIBE });`,
    )
    .join("\n");
  return `${HEADER}
//
// Side-effect registration of each generated command's detect() predicate and
// DESCRIBE text, keyed by HTTP route segment. Imported once at server startup
// (src/http/routes.ts) to back /commands/:bc/:name/describe and /detect.
import { register } from "./registry.js";
${imports}

${regs}
`;
}
