// Pure content emitters for the deterministic scaffold. Each takes descriptors
// and returns a file's text — no I/O, so they are trivially testable and the
// generator (generate.ts) decides when to write.

import type { CommandDescriptor } from "./introspect.js";

const HEADER = `// ⚙️  GENERATED by src/kernel/codegen — DO NOT EDIT.`;

/** The {command}.gen.ts skeleton: role check + arg validation + call into apply(). */
export function genContent(d: CommandDescriptor): string {
  const validators = [...new Set(d.fields.filter((f) => f.required && f.validator).map((f) => f.validator!))].sort();
  const validatorImport = validators.length
    ? `import { ${validators.join(", ")} } from "../../util/invariants.js";\n`
    : "";
  const argsType = `${d.commandName}Args`;
  const fieldLines = d.fields.map((f) => `  ${f.name}${f.required ? "" : "?"}: ${f.tsType};`).join("\n");
  const validationLines = d.fields
    .filter((f) => f.required && f.validator)
    .map((f) => `  ${f.validator}(${JSON.stringify(f.name)}, args.${f.name});`)
    .join("\n");

  return `${HEADER}
//
// Deterministic command skeleton for "${d.eventName}" (command ${d.commandName},
// bounded context ${d.boundedContext}). The role check, argument validation and
// wiring are derived from the Qlerify model and cannot drift from it.
//
// Business logic (apply), the event-detection predicate (detect) and the human-
// readable description (DESCRIBE) live in ./${d.kebab}.logic.ts — the AI/hand-
// authored region. Regen rule: THIS file is overwritten from the model; the
// .logic.ts file is preserved.
import { assertRole, type Role } from "../../auth.js";
${validatorImport}import { apply } from "./${d.kebab}.logic.js";

export interface ${argsType} {
${fieldLines}
}

/** ${d.eventName} — emitted by role "${d.role}". */
export async function ${d.handlerName}(args: ${argsType}, role: Role) {
  assertRole(role, ${JSON.stringify(d.role)});
${validationLines ? validationLines + "\n" : ""}  return apply({ args, role });
}
`;
}

/** The aggregate's commands.ts barrel: a stable import surface. */
export function barrelContent(ds: CommandDescriptor[], aggregate: string, bc: string): string {
  const exports = ds.map((d) => `export { ${d.handlerName} } from "./${d.kebab}.gen.js";`).join("\n");
  return `${HEADER}
//
// Public command surface for the ${aggregate} aggregate (${bc}). Re-exports the
// generated handlers so existing importers (HTTP routes, the simulator runner,
// tests) keep a stable path: src/${bc.toLowerCase()}/${ds[0]?.aggDir ?? ""}/commands.ts.
${exports}
`;
}

/** src/commands/registry.generated.ts — side-effect registration of every
 * generated command: its handler (from .gen.ts) plus detect/DESCRIBE (from
 * .logic.ts). Imported once at startup so the HTTP layer can mount routes and
 * serve /describe + /detect for the whole generated command set. */
export function registryContent(ds: CommandDescriptor[]): string {
  const imports = ds
    .map(
      (d) =>
        `import { ${d.handlerName} } from "../${d.bcDir}/${d.aggDir}/${d.kebab}.gen.js";\n` +
        `import * as ${d.handlerName}Logic from "../${d.bcDir}/${d.aggDir}/${d.kebab}.logic.js";`,
    )
    .join("\n");
  const regs = ds
    .map(
      (d) =>
        `register(${JSON.stringify(d.kebab)}, { commandName: ${JSON.stringify(d.commandName)}, boundedContext: ${JSON.stringify(d.boundedContext)}, handlerName: ${JSON.stringify(d.handlerName)}, route: ${JSON.stringify(`/commands/${d.bcDir}/${d.kebab}`)}, eventRef: ${JSON.stringify(d.eventRef)}, role: ${JSON.stringify(d.role)}, handler: ${d.handlerName}, detect: ${d.handlerName}Logic.detect, DESCRIBE: ${d.handlerName}Logic.DESCRIBE });`,
    )
    .join("\n");
  return `${HEADER}
//
// Side-effect registration of each generated command (handler + detect +
// DESCRIBE), keyed by HTTP route segment. Imported once at server startup
// (src/http/routes.ts) to mount routes and back /describe and /detect.
import { register } from "./registry.js";
${imports}

${regs}
`;
}

/** The default .logic.ts written for a command that has no hand/AI-authored
 * logic yet (e.g. a brand-new command, including after a model swap). It is a
 * thin delegate to the GENERIC BASE COMMAND (src/commands/base.ts), so the
 * command WORKS immediately — it creates/updates its aggregate from the command
 * fields + the entity's example data and emits the event, with no AI. The base
 * looks the command up in the live model by name on every call, so this stub
 * carries no model data and stays correct across hot reloads.
 *
 * Authoring real logic = replace this file with apply()/detect()/DESCRIBE that
 * import nothing from base.js (like the SAP commands). The generator NEVER
 * overwrites an existing .logic.ts, so the override is a clean file swap. */
export function logicStubContent(d: CommandDescriptor): string {
  return `// 🌱 GENERATED default logic for "${d.eventName}" (${d.commandName}).
// Delegates to the generic base command — create/update the ${d.aggregate} from
// the command fields + example data, then emit the event. This WORKS as-is.
// To add preconditions, status transitions, or cross-aggregate effects, replace
// this file with a real apply()/detect()/DESCRIBE (import nothing from base.js),
// by hand or via:  npm run codegen:ai -- ${d.commandName} ${d.boundedContext}
// The deterministic generator never overwrites this file once it exists.
import { genericApply, genericDetect, genericDescribe } from "../../commands/base.js";
import type { CommandContext, DetectInput, DetectResult } from "../../commands/runtime.js";
import type { ${d.commandName}Args } from "./${d.kebab}.gen.js";

const COMMAND = "${d.commandName}";

export async function apply(ctx: CommandContext<${d.commandName}Args>): Promise<unknown> {
  return genericApply(COMMAND, ctx);
}

export async function detect(input: DetectInput): Promise<DetectResult> {
  return genericDetect(COMMAND, input);
}

export const DESCRIBE = genericDescribe(COMMAND);
`;
}
