// Deterministic Prisma schema generation from the ontology's entities.
//
// Each model entity becomes a Prisma model: scalar columns from its fields
// (dataType-mapped), `id` as the primary key, required fields non-null and the
// rest nullable, plus the platform columns every aggregate carries (version for
// optimistic locking, created/updated timestamps). Cross-entity references stay
// as plain string FK columns (no @relation) — the same "honor the boundary"
// convention the hand-written schema already uses across bounded contexts, and
// the safe generic choice when ownership isn't explicit in the model.
//
// The append-only EventLog table is infrastructure, not domain — it is emitted
// verbatim so a model swap never touches the immutable event log's shape.
//
// This module only PRODUCES text. Applying it (and the destructive table drops
// that implies) is the swap orchestrator's job (swap.ts), behind a warning.

import { getOntology, type EntitySchema } from "../../ontology/model.js";

const PRISMA_HEADER = `// ⚙️  GENERATED by src/kernel/codegen/schema.ts from the active Qlerify workflow model — DO NOT EDIT.
// Regenerate via the swap orchestrator (npm run swap). Hand edits are overwritten.

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "sqlite"
  // Absolute path via DATABASE_URL (see prisma/schema.prisma for why a relative
  // file:./dev.db silently splits CLI and runtime onto two different .db files).
  url      = env("DATABASE_URL")
}`;

// The infra table is domain-agnostic and preserved verbatim across swaps. It
// MUST mirror prisma/schema.prisma's EventLog exactly — a swap regenerates the
// schema from this text, and any column missing here (businessAtKind,
// evidenceKind, tenancy/actor columns, …) gets DROPPED by `prisma db push` and
// breaks every emit against the regenerated client.
const EVENT_LOG_MODEL = `// ---------------------------------------------------------------------------
// Platform infrastructure — append-only event log (domain-agnostic, preserved
// verbatim across every model swap).
// ---------------------------------------------------------------------------

model EventLog {
  id             String   @id @default(uuid())
  eventName      String
  eventRef       String
  boundedContext String
  aggregateRoot  String
  aggregateId    String
  caseId         String?  // correlation id: the case (end-to-end run) this event belongs to
  role           String
  payload        String   // JSON-serialized command args
  occurredAt     DateTime @default(now())  // real wall-clock time the event was recorded
  businessAt     DateTime? // business time; null = no source anchor (moment unknown, never faked)
  businessAtKind String?  // known | estimated | null (see prisma/schema.prisma)
  provenance     String?  // simulated | recorded | live
  evidenceKind   String?  // derivation scenario: create | status | fields | none
  evidence       String?  // human-readable evidence reason
  organizationId String?
  workflowId     String?
  actorPrincipalId String?
  actorKind        String?

  @@index([occurredAt])
  @@index([eventRef])
  @@index([caseId, occurredAt])
  @@index([organizationId, occurredAt])
  @@index([workflowId, occurredAt])
  @@index([workflowId, actorKind])
  @@index([workflowId, aggregateId])
  @@index([workflowId, eventRef, aggregateId])
}`;

function prismaType(dataType?: string): string {
  switch ((dataType ?? "string").toLowerCase()) {
    case "number":
    case "integer":
      return "Int";
    case "boolean":
      return "Boolean";
    case "float":
    case "decimal":
      return "Float";
    default:
      return "String";
  }
}

/** Pad a model field declaration so columns line up like the hand-written schema. */
function fieldLine(name: string, type: string, attrs: string): string {
  return `  ${name.padEnd(20)}${type.padEnd(9)}${attrs}`.trimEnd();
}

function modelFor(entity: EntitySchema): string {
  const required = new Set(entity.required ?? []);
  const declared = new Set(entity.fields.map((f) => f.name));
  const lines: string[] = [];

  if (entity.description) lines.push(`// ${entity.description}`);
  lines.push(`model ${entity.name} {`);

  for (const f of entity.fields) {
    if (f.name === "id") {
      lines.push(fieldLine("id", "String", "@id"));
      continue;
    }
    const type = prismaType(f.dataType);
    const optional = required.has(f.name) ? "" : "?";
    const note = f.description ? `  // ${f.description}` : "";
    lines.push(fieldLine(f.name, type + optional, "") + note);
  }

  // Platform columns (only if the model didn't already declare them). The
  // timestamps are NULLABLE: ingested rows carry only what the source recorded
  // (a missing creation date is NULL, never an ingestion-time stamp — see
  // packs/ingest.ts); the defaults still stamp genuine time on live writes.
  if (!declared.has("version")) lines.push(fieldLine("version", "Int", "@default(0)"));
  if (!declared.has("createdAt")) lines.push(fieldLine("createdAt", "DateTime?", "@default(now())"));
  if (!declared.has("updatedAt")) lines.push(fieldLine("updatedAt", "DateTime?", "@updatedAt"));

  lines.push("}");
  return lines.join("\n");
}

/** The generated schema.prisma text for the current (or a given) ontology. */
export function generateSchema(ontology = getOntology()): string {
  const byBc = new Map<string, EntitySchema[]>();
  for (const e of ontology.entities) {
    const bc = ontology.boundedContextOf(e.name) ?? "Unassigned";
    (byBc.get(bc) ?? byBc.set(bc, []).get(bc)!).push(e);
  }

  const sections: string[] = [PRISMA_HEADER];
  for (const bc of [...byBc.keys()].sort()) {
    sections.push(
      `// ---------------------------------------------------------------------------\n` +
        `// ${bc} bounded context\n` +
        `// ---------------------------------------------------------------------------`,
    );
    for (const e of byBc.get(bc)!.sort((a, b) => a.name.localeCompare(b.name))) {
      sections.push(modelFor(e));
    }
  }
  sections.push(EVENT_LOG_MODEL);
  return sections.join("\n\n") + "\n";
}

/** Entity name → Prisma model/table name (currently identity). */
export function entityTableNames(ontology = getOntology()): string[] {
  return ontology.entities.map((e) => e.name).sort();
}
