// Model-swap orchestrator.
//
// When the live model (workflow.json) is replaced with a different domain, this
// reconfigures everything DETERMINISTIC — the Prisma projection tables, the
// command skeletons, stubbed logic for new commands, and a fresh overlay — and
// reports the irreversible data loss and the domain-authored files that still
// need (re)authoring. Roles, the event registry order/phase, and HTTP command
// routes are already model/overlay-derived and reconfigure on their own.
//
// SAFETY: dropping projection tables is irreversible. swapPreview() is read-only
// and is what the UI shows; applySwap() performs the destructive work and only
// runs from the CLI with an explicit --yes.

import { readFileSync, writeFileSync, copyFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getOntology, QLERIFY_DIR } from "../../ontology/model.js";
import { generateSchema, entityTableNames } from "./schema.js";
import { generateBoundedContext } from "./generate.js";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..", "..", "..");
const SCHEMA_PATH = join(ROOT, "prisma", "schema.prisma");
const OVERLAY_PATH = join(QLERIFY_DIR, "overlay.json");

// Infra table that is never a projection and never dropped.
const INFRA_TABLES = new Set(["EventLog"]);

// Domain-authored files (the AI/hand bucket) that a swap cannot generate
// deterministically — listed so the operator knows what remains after the swap.
const DOMAIN_AUTHORED = [
  "src/<bc>/<aggregate>/*.logic.ts — apply()/detect() bodies (stubbed; author or `npm run codegen:ai`)",
  "web/app.js — column hints (or wire to /api/ontology)",
];

function currentTables(): string[] {
  if (!existsSync(SCHEMA_PATH)) return [];
  const text = readFileSync(SCHEMA_PATH, "utf-8");
  return [...text.matchAll(/^model\s+(\w+)\s*\{/gm)].map((m) => m[1]!);
}

export interface SwapPreview {
  newModelTables: string[];
  currentTables: string[];
  dropped: string[]; // exist now, gone in new model → DATA PERMANENTLY LOST
  created: string[]; // new in the model → tables created empty
  kept: string[]; // in both (schema may still change)
  eventLogPreserved: boolean;
  irreversible: boolean;
  boundedContexts: string[];
  domainAuthoredToReauthor: string[];
}

/** Read-only diff of what applying the current model would do to the DB. */
export function swapPreview(): SwapPreview {
  const ont = getOntology();
  const newTables = entityTableNames(ont);
  const newSet = new Set(newTables);
  const current = currentTables();

  const dropped = current.filter((t) => !INFRA_TABLES.has(t) && !newSet.has(t));
  const created = newTables.filter((t) => !current.includes(t));
  const kept = newTables.filter((t) => current.includes(t));

  return {
    newModelTables: newTables,
    currentTables: current,
    dropped,
    created,
    kept,
    eventLogPreserved: true,
    irreversible: dropped.length > 0,
    boundedContexts: ont.boundedContexts,
    domainAuthoredToReauthor: DOMAIN_AUTHORED,
  };
}

/** A fresh overlay for the new model: order = topological index, phase = 1.
 * Replaces the old overlay (whose keys would no longer resolve), preserving the
 * loader's validation invariant. */
function freshOverlay(): string {
  const ont = getOntology();
  const order = ont.topologicalOrder();
  const events: Record<string, { order: number; phase: number }> = {};
  order.forEach((key, i) => {
    events[key] = { order: i, phase: 1 };
  });
  return JSON.stringify(
    {
      $comment:
        "Regenerated by the swap orchestrator. order = topological index, phase = 1. Curate these to restore a multi-act demo ordering.",
      events,
    },
    null,
    2,
  ) + "\n";
}

export interface SwapResult {
  preview: SwapPreview;
  schemaWritten: boolean;
  overlayWritten: boolean;
  generated: Array<{ bc: string; written: number }>;
}

/** Perform the destructive swap. Writes the new schema, a fresh overlay, and the
 * command skeletons (+ stub logic) for every bounded context, then the caller is
 * responsible for `prisma db push --accept-data-loss`. */
export function applySwap(): SwapResult {
  const preview = swapPreview();

  // Back up the schema before overwriting (one level of undo for the file; the
  // DROPPED TABLE DATA is gone once db push runs).
  if (existsSync(SCHEMA_PATH)) copyFileSync(SCHEMA_PATH, SCHEMA_PATH + ".bak");
  writeFileSync(SCHEMA_PATH, generateSchema());
  writeFileSync(OVERLAY_PATH, freshOverlay());

  const generated = getOntology().boundedContexts.map((bc) => {
    try {
      const r = generateBoundedContext(bc);
      return { bc, written: r.written.length };
    } catch {
      return { bc, written: 0 }; // a BC with no commands — skip
    }
  });

  return { preview, schemaWritten: true, overlayWritten: true, generated };
}

// ---------------------------------------------------------------------------
// CLI — default is a SAFE dry-run preview. Destructive apply needs --yes.
// ---------------------------------------------------------------------------

function printWarning(p: SwapPreview): void {
  const line = "─".repeat(72);
  console.log(`\n${line}`);
  console.log("⚠️   MODEL SWAP — DESTRUCTIVE, IRREVERSIBLE");
  console.log(line);
  if (p.dropped.length) {
    console.log(`\n🗑️   These projection tables will be DROPPED and their data`);
    console.log(`    PERMANENTLY LOST. This CANNOT be undone:`);
    for (const t of p.dropped) console.log(`      • ${t}`);
  } else {
    console.log(`\n(no existing tables will be dropped)`);
  }
  if (p.created.length) {
    console.log(`\n🆕  Created (empty):`);
    for (const t of p.created) console.log(`      • ${t}`);
  }
  if (p.kept.length) console.log(`\n♻️   Kept (schema may change): ${p.kept.join(", ")}`);
  console.log(`\n📜  Preserved: the append-only EventLog (immutable history is never dropped).`);
  console.log(`\n✍️   Deterministically reconfigured: Prisma schema, roles, event`);
  console.log(`    order/phase, command skeletons, HTTP command routes.`);
  console.log(`\n🧠  Still needs (re)authoring — the AI/hand-written domain code:`);
  for (const f of p.domainAuthoredToReauthor) console.log(`      • ${f}`);
  console.log(`\n${line}`);
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const preview = swapPreview();
  printWarning(preview);
  if (!process.argv.includes("--yes")) {
    console.log(`\nThis was a DRY RUN. No files or tables were changed.`);
    console.log(`Re-run with --yes to apply, then: npx prisma db push --accept-data-loss\n`);
    process.exit(0);
  }
  console.log(`\n--yes given → applying swap...\n`);
  const result = applySwap();
  for (const g of result.generated) console.log(`  codegen ${g.bc}: ${g.written} file(s)`);
  console.log(`\n✅ Schema + overlay + skeletons written.`);
  console.log(`   Now run:  npx prisma db push --accept-data-loss --skip-generate && npx prisma generate`);
  console.log(`   Then author the stubbed *.logic.ts and the domain files listed above.\n`);
}
